language: node_js
node_js:
  - "8.9.0"
  - "9"
  - "10"
  - node

before_install:
  - export NODE_ENV=production
install:
  - npm install
  - npm run build
  - export NODE_ENV=dev
  - npm install
script:
  - npm run eslint
